### ISSUE TITLE
Celery tasks don't seem to run under docker_django3.1

### ISSUE THREAD

**Issue by robsee** [samuelclay/NewsBlur#1410]
All of the celery services are running, but it doesn't look like any of the tasks ever get fired.

Also, when I try Feed.drain_task_feeds() mentioned in Maintenance, I get the following error:
[Feb 15 14:07:56]  ---> Draining 0 tasked feeds...
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/srv/newsblur/apps/rss_feeds/models.py", line 581, in drain_task_feeds
    r.sadd('queued_feeds', *tasked_feeds)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 2243, in sadd
    return self.execute_command('SADD', name, *values)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'sadd' command

**Comment by robsee** [comment]
think this might be because app = Celery('newsblur') instead of app = Celery('newsblur_web') in celeryapp.py in newsblur_web

**Comment by samuelclay** [comment]
This has been fixed on the `dashboard3` branch. I'm going to continue hooking up these parts together this week, so I am hoping to get to the celery servers soon.
