### ISSUE TITLE
error running refresh_feeds manually

### ISSUE THREAD

**Issue by robsee** [samuelclay/NewsBlur#1412]
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/srv/newsblur/apps/rss_feeds/management/commands/refresh_feeds.py", line 61, in handle
    f.set_next_scheduled_update()
  File "/srv/newsblur/apps/rss_feeds/models.py", line 2209, in set_next_scheduled_update
    random_factor = random.randint(0, total) / 4
  File "/usr/local/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/usr/local/lib/python3.7/random.py", line 195, in randrange
    raise ValueError("non-integer stop for randrange()")
ValueError: non-integer stop for randrange()

Fixed by changing /srv/newsblur/apps/rss_feeds/models.py", line 2209 to
random_factor = random.randint(0, int(total)) / 4

**Comment by samuelclay** [comment]
This is fixed in the `dashboard3` branch.
