### ISSUE TITLE
Search isn't working yet with docker/dashboard3

### ISSUE THREAD

**Issue by robsee** [samuelclay/NewsBlur#1432]
Any time I try and do a search I get the following output in the logs. I've run index feeds and index stories through manage.py without any success.  Any suggestions ?
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/newsblur/utils/json_functions.py", line 117, in wrap
    response = func(request, *a, **kw)
  File "/srv/newsblur/apps/reader/views.py", line 667, in load_single_feed
    stories = feed.find_stories(query, order=order, offset=offset, limit=limit)
  File "/srv/newsblur/apps/rss_feeds/models.py", line 1852, in find_stories
    story_ids = SearchStory.query(feed_ids=[self.pk], query=query, order=order,
  File "/srv/newsblur/apps/search/models.py", line 280, in query
    def query(cls, feed_ids, query, order, offset, limit, strip=False):
  File "/srv/newsblur/apps/search/models.py", line 207, in create_elasticsearch_mapping
    cls.ES.indices.delete_index_if_exists("%s-index" % cls.name)
  File "/usr/local/lib/python3.9/site-packages/pyes/managers.py", line 176, in create_index_if_missing
    return self.create_index(index, settings)
  File "/usr/local/lib/python3.9/site-packages/pyes/managers.py", line 165, in create_index
    return self.conn._send_request('PUT', index, settings)
  File "/usr/local/lib/python3.9/site-packages/pyes/es.py", line 486, in _send_request
    raise_if_error(response.status, decoded)
  File "/usr/local/lib/python3.9/site-packages/pyes/convert_errors.py", line 74, in raise_if_error
    bits = error.split('[', 1)

**Comment by samuelclay** [comment]
Thanks for reporting this! Just confirmed that it doens't work with docker-compose, and in fact it's not working on https://beta.newsblur.com. Will fix soon.

**Comment by samuelclay** [comment]
Should be working fine now.
