### ISSUE TITLE
Problem building docker compose

### ISSUE THREAD

**Issue by marksnyder** [samuelclay/NewsBlur#1444]
**Hello, trying to build Dashboard3. When I run make nb I get the following. Any ideas on what I may be doing wrong?**

docker-compose exec newsblur_web ./manage.py migrate
ERROR: 137
make: [Makefile:21: nb] Error 137 (ignored)
docker-compose exec newsblur_web ./manage.py loaddata config/fixtures/bootstrap.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/newsblur/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 777, in save_base
    pre_save.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sites/models.py", line 114, in clear_site_cache
    del SITE_CACHE[Site.objects.using(using).get(pk=instance.pk).domain]
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: Problem installing fixture '/srv/newsblur/config/fixtures/bootstrap.json': Could not load sites.Site(pk=1): relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^

ERROR: 1
make: [Makefile:22: nb] Error 1 (ignored)

**Comment by marksnyder** [comment]
seems like latest commits fixed

**Comment by samuelclay** [comment]
Whew, that would've stumped me otherwise.

**Comment by samuelclay** [comment]
Everything work out OK? We're still buttoning everything up but we're getting closer. And try out beta.newsblur.com if you haven't already.

**Comment by marksnyder** [comment]
Unfortunately haven't been able to get it up and running yet. I get this error whet I start the docker containers:

node                | internal/modules/cjs/loader.js:1032
node                |   throw err;
node                |   ^
node                |
node                | Error: Cannot find module '@sentry/node'
node                | Require stack:
node                | - /srv/newsblur.js
node                |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
node                |     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
node                |     at Module.require (internal/modules/cjs/loader.js:1089:19)
node                |     at require (internal/modules/cjs/helpers.js:73:18)
node                |     at Object.<anonymous> (/srv/newsblur.js:5:12)
node                |     at Object.<anonymous> (/srv/newsblur.js:74:4)
node                |     at Module._compile (internal/modules/cjs/loader.js:1200:30)
node                |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
node                |     at Module.load (internal/modules/cjs/loader.js:1049:32)
node                |     at Function.Module._load (internal/modules/cjs/loader.js:937:14) {
node                |   code: 'MODULE_NOT_FOUND',
node                |   requireStack: [ '/srv/newsblur.js' ]
node                | }

**Comment by samuelclay** [comment]
Sounds like `npm install` didn't run correctly. I added some new dependencies on node when I put the four node servers together.
