### ISSUE TITLE
Android: Freeeform multiwindow & split screen related crashes

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1609]
**Crash logs**

```
FATAL EXCEPTION: main
Process: com.newsblur, PID: 1563
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.newsblur/com.newsblur.activity.ReadStoriesReading}: java.lang.IllegalStateException: Fragment already added: ReadingPagerFragment{559b6b8} (cbb318d3-a13e-4911-8d64-9fe2be1ec86f id=0x7f0a0045 tag=com.newsblur.fragment.ReadingPagerFragment)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Fragment already added: ReadingPagerFragment{559b6b8} (cbb318d3-a13e-4911-8d64-9fe2be1ec86f id=0x7f0a0045 tag=com.newsblur.fragment.ReadingPagerFragment)
	at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:92)
	at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1422)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:1906)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1814)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7043)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2744)
	... 9 more
```
**Device details**
App version: 11.2 (199)
Android: 8.1.0
Model: Lenovo Tab4 8 plus (TB-8704X)

App crashed while reopened the app from device recents after a long period of time.
(_please change the issue title_)

**Comment by shuvashish76** [comment]
Similar crash when
1 open any article in the app
2. perform "freeeform multiwindow" or "split screen"
3. App crashes

<details>
  <summary>Crash logs</summary>

```
FATAL EXCEPTION: main
Process: com.newsblur, PID: 20852
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.newsblur/com.newsblur.activity.ReadStoriesReading}: java.lang.IllegalStateException: Fragment already added: ReadingPagerFragment{e9e045b} (f6780c8f-11db-4437-be3e-23ccd033ede9 id=0x7f0a0045 tag=com.newsblur.fragment.ReadingPagerFragment)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4702)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Fragment already added: ReadingPagerFragment{e9e045b} (f6780c8f-11db-4437-be3e-23ccd033ede9 id=0x7f0a0045 tag=com.newsblur.fragment.ReadingPagerFragment)
	at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:92)
	at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1422)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:387)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:1906)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1814)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1335)
	at android.app.Activity.performStart(Activity.java:7043)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2744)
	... 10 more
```

**Comment by sictiru** [comment]
@shuvashish76 The issue has fixed as part of https://github.com/samuelclay/NewsBlur/issues/1598. 
Please update to the latest version of NewsBlur 11.2.2 and let us know if you still encounter the issue.

**Comment by shuvashish76** [comment]
Thanks `v11.2.2 (201)` working :)

But another issue with split screen

https://user-images.githubusercontent.com/48226312/151745405-734b36aa-6d26-45b1-9c61-6296b168bffb.mp4

**Comment by shuvashish76** [comment]
Closing in favor of #1618
