### ISSUE TITLE
Android: Crash on Flat folder view

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1628]
**Steps to produce:**
1. Click on 3 dot menu
2. Mute sites
3. Again click on top-right 3 dot menu
4. Folder View > Flat

**Crash logs:**
```
FATAL EXCEPTION: main
Process: com.newsblur, PID: 10558
java.lang.NullPointerException: rhs == null
	at java.lang.String.compareTo(Native Method)
	at com.newsblur.activity.FeedChooserAdapter.lambda$getListComparator$0(FeedChooserAdapter.java:200)
	at com.newsblur.activity.FeedChooserAdapter.$r8$lambda$XPOo_oJ4DEu1xkj2PuzVZoFZMBo(Unknown Source:0)
	at com.newsblur.activity.FeedChooserAdapter$$ExternalSyntheticLambda0.compare(Unknown Source:6)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1498)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:201)
	at com.newsblur.activity.FeedChooserAdapter.notifyDataChanged(FeedChooserAdapter.java:182)
	at com.newsblur.activity.FeedChooserAdapter.setData(FeedChooserAdapter.java:163)
	at com.newsblur.activity.FeedChooser.setAdapterData(FeedChooser.java:146)
	at com.newsblur.activity.MuteConfig.setAdapterData(MuteConfig.java:114)
	at com.newsblur.activity.FeedChooser.replaceFolderView(FeedChooser.java:167)
	at com.newsblur.activity.FeedChooser.onOptionsItemSelected(FeedChooser.java:133)
	at com.newsblur.activity.MuteConfig.onOptionsItemSelected(MuteConfig.java:56)
	at android.app.Activity.onMenuItemSelected(Activity.java:3464)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:328)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1181)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3150)
	at android.widget.AbsListView.onTouchUp(AbsListView.java:4117)
	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3862)
	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:217)
	at android.view.View.dispatchTouchEvent(View.java:11777)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2962)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2406)
	at android.view.View.dispatchPointerEvent(View.java:12016)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4809)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4623)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4161)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4214)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4180)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4307)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4188)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4364)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4161)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4214)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4180)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4188)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4161)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6682)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6656)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6617)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6785)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Then whenever I open the app & just click on "Mute sites" it crashes.

```
FATAL EXCEPTION: main
Process: com.newsblur, PID: 11004
java.lang.NullPointerException: rhs == null
	at java.lang.String.compareTo(Native Method)
	at com.newsblur.activity.FeedChooserAdapter.lambda$getListComparator$0(FeedChooserAdapter.java:200)
	at com.newsblur.activity.FeedChooserAdapter.$r8$lambda$XPOo_oJ4DEu1xkj2PuzVZoFZMBo(Unknown Source:0)
	at com.newsblur.activity.FeedChooserAdapter$$ExternalSyntheticLambda0.compare(Unknown Source:6)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1498)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:201)
	at com.newsblur.activity.FeedChooserAdapter.notifyDataChanged(FeedChooserAdapter.java:182)
	at com.newsblur.activity.FeedChooserAdapter.setData(FeedChooserAdapter.java:163)
	at com.newsblur.activity.FeedChooser.setAdapterData(FeedChooser.java:146)
	at com.newsblur.activity.MuteConfig.setAdapterData(MuteConfig.java:114)
	at com.newsblur.activity.MuteConfig.processData(MuteConfig.java:100)
	at com.newsblur.activity.MuteConfig.processFeeds(MuteConfig.java:82)
	at com.newsblur.activity.FeedChooser$$ExternalSyntheticLambda0.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Android  : _8.1.0_
App version : _11.2.2 (201)_

**Comment by sictiru** [comment]
There are feed instances that have missing data like title. Added check to handle such cases.
