### ISSUE TITLE
"Remote end closed connection without response" exceptions when trying to automate writing API data to a file.

### ISSUE THREAD

**Issue by NylaTheWolf** [samuelclay/NewsBlur#1688]
So I wrote a Python script to automate writing multiple pages of a feed (from `/reader/feed/:id`) to a file, and it worked fine several days ago. However, since yesterday I've been experiencing these exceptions and I can't figure out what's wrong. I don't know if it's the server cutting me off, something wrong with my script, or if there's an error with the requests module.

This is my script. The feed I'm trying to get is a subreddit feed, if that helps.
```
import requests
import json
import time
session = requests.Session()
login_payload = {"username": "NylaTheWolf",
        "password": "password"}
session.post("https://newsblur.com/api/login", data=login_payload)

with open("2022-05-19 Newsblur test.txt", "w") as f:
    for page_number in range (1,31):
        response = session.get(f"https://newsblur.com/reader/feed/1090346?page={page_number}")
        pretty_response = json.loads(response.text)
        f.write(json.dumps(pretty_response, indent=2))
        f.write("\n")
        if (page_number %5 == 0):
            time.sleep(10)
```

This is the response I get:

```
Traceback (most recent call last):
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Victoria Redacted\Documents\RSS\202205011812_newsblur_script_write.py", line 11, in <module>
    response = session.get(f"https://newsblur.com/reader/feed/1090346?page={page_number}")
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

I'm new to this stuff so I'm not exactly sure how to interpret these errors. This error occurred on another subreddit feed.

Oddly enough, for both subreddits, doing range 1-11 worked fine. For the subreddit in the example (r/gamedev), ranges 21-31 worked fine. The other one got the error at some point when I tried 21-31 (some pages were written. It seemed to have gotten the error on page 25 or 26 if I remember correctly).

If I try 31-51 for r/gamedev, however:
```
Traceback (most recent call last):
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Victoria Redacted\Documents\RSS\202205011812_newsblur_script_write.py", line 11, in <module>
    response = session.get(f"https://newsblur.com/reader/feed/1090346?page={page_number}")
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Victoria Redacted\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

It seems like it stopped after writing page 35.

I'm not sure if this is the right place to talk about this issue but I figured it was worth bringing to your attention.

Thank you for all your hard work on Newsblur!

**Comment by samuelclay** [comment]
This is what I see when I run a simplified version:

```
>>> import requests
>>> session = requests.Session()
>>> for page in range(0,100):
...   resp = session.get(f"https://newsblur.com/reader/feed/1090346?page={page}")
...   print(len(resp.text))
... 
2363
30861
35079
28368
29648
25774
29327
29266
29607
30193
30825
27089
29104
28290
28667
29025
29108
28440
28715
29192
28190
28952
25728
27330
28333
27440
28243
26865
26897
27897
27943
29486
28174
29033
27365
32579
28548
29107
29763
26603
30774
28935
29648
26451
28094
32382
27686
27011
28423
28758
28075
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
```

What do you see if you run that?

**Comment by NylaTheWolf** [comment]
I get something very similar:

```
2363
28855
30172
34618
29025
29369
25313
31777
27091
29404
30025
31608
27309
28577
28577
28796
28522
29621
28530
29464
28158
28840
27974
26031
28428
26706
27778
28373
26702
26780
27690
29189
28311
29350
28461
28028
31205
30563
28041
29357
26358
30557
30596
28476
26413
28123
32299
27580
27495
27695
29250
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15570
15571
15570
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
15571
```

**Comment by samuelclay** [comment]
I ran your script multiple times and it runs fine. It does create a non-quite JSON file with every response appended, so you'll have to do some work to parse that later. Consider a SQLite DB or something else a tad bit more structured. But I have no idea why this would happen and I don't think NewsBlur's servers are cutting off the connection. There are rate limiters but not on that endpoint.
