### ISSUE TITLE
Docker issues with Postgres and Mongo

### ISSUE THREAD

**Issue by JStyle21** [samuelclay/NewsBlur#1689]
Hi,

Tried to run the docker container and got some strange postgres issues.

I can see it is restarting itself
```
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED         STATUS                           PORTS                                                                                                                 NAMES
6bf77340b279   haproxy:latest                                         "docker-entrypoint.s…"   6 minutes ago   Up 5 minutes                     0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:1936->1936/tcp, :::1936->1936/tcp   haproxy
ad1630b238d4   nginx:1.19.6                                           "/docker-entrypoint.…"   6 minutes ago   Up 6 minutes                     80/tcp, 0.0.0.0:81->81/tcp, :::81->81/tcp                                                                             nginx
8596a0ec897b   newsblur/newsblur_python3:latest                       "/bin/sh -c newsblur…"   6 minutes ago   Up 6 minutes                     0.0.0.0:8000->8000/tcp, :::8000->8000/tcp                                                                             newsblur_web
3fb35cb5d208   newsblur/newsblur_node:latest                          "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes                     0.0.0.0:8008->8008/tcp, :::8008->8008/tcp                                                                             node
cd03bef3c10a   postgres:13.1                                          "docker-entrypoint.s…"   6 minutes ago   Restarting (1) 6 seconds ago                                                                                                                           db_postgres
53dcca347315   newsblur/newsblur_python3                              "celery worker -A ne…"   6 minutes ago   Up 6 minutes                                                                                                                                           task_celery
93b2995f423c   docker.elastic.co/elasticsearch/elasticsearch:7.16.3   "/bin/tini -- /usr/l…"   6 minutes ago   Up 6 minutes                     0.0.0.0:9200->9200/tcp, :::9200->9200/tcp, 0.0.0.0:9300->9300/tcp, :::9300->9300/tcp                                  db_elasticsearch
e65e93fa26a8   yusukeito/imageproxy:v0.11.2                           "/app/imageproxy -ad…"   6 minutes ago   Restarting (1) 9 seconds ago                                                                                                                           imageproxy
4bc92905cee1   redis:latest                                           "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes                     6379/tcp, 0.0.0.0:6579->6579/tcp, :::6579->6579/tcp                                                                   db_redis
e40e4a48cc94   mongo:4.0                                              "docker-entrypoint.s…"   6 minutes ago   Restarting (14) 57 seconds ago                                                                               
```

```
docker pull newsblur/newsblur_python3
Using default tag: latest
latest: Pulling from newsblur/newsblur_python3
Digest: sha256:9edec306a7f9a68993325a70f8b0795b4462bcf9d08e7256dc4407dee5b22603
Status: Image is up to date for newsblur/newsblur_python3:latest
docker.io/newsblur/newsblur_python3:latest
docker pull newsblur/newsblur_node
Using default tag: latest
latest: Pulling from newsblur/newsblur_node
Digest: sha256:307471b66f895bb24ad924322b0c8cf0f6afa908fcee380aa5489615a2ad1859
Status: Image is up to date for newsblur/newsblur_node:latest
docker.io/newsblur/newsblur_node:latest
docker pull newsblur/newsblur_monitor
Using default tag: latest
latest: Pulling from newsblur/newsblur_monitor
Digest: sha256:347974295453b92397e13e2bb4b51e25e626e475e80fdf098cf98f680e2d3210
Status: Image is up to date for newsblur/newsblur_monitor:latest
docker.io/newsblur/newsblur_monitor:latest
RUNWITHMAKEBUILD=True CURRENT_UID=1000 CURRENT_GID=100 docker-compose down
Stopping haproxy          ... done
Stopping nginx            ... done
Stopping newsblur_web     ... done
Stopping node             ... done
Stopping db_redis         ... done
Stopping db_postgres      ... done
Stopping db_elasticsearch ... done
Stopping db_mongo         ... done
Stopping imageproxy       ... done
Stopping task_celery      ... done
Removing haproxy          ... done
Removing nginx            ... done
Removing newsblur_web     ... done
Removing node             ... done
Removing db_redis         ... done
Removing db_postgres      ... done
Removing db_elasticsearch ... done
Removing db_mongo         ... done
Removing imageproxy       ... done
Removing task_celery      ... done
Removing network newsblur_default
[[ -d config/certificates ]] && echo "keys exist" || make keys
keys exist
RUNWITHMAKEBUILD=True CURRENT_UID=1000 CURRENT_GID=100 docker-compose up -d --build --remove-orphans
Creating network "newsblur_default" with the default driver
Creating db_redis         ... done
Creating db_mongo         ... done
Creating imageproxy       ... done
Creating db_postgres      ... done
Creating task_celery      ... done
Creating db_elasticsearch ... done
Creating node             ... done
Creating newsblur_web     ... done
Creating nginx            ... done
Creating haproxy          ... done
docker exec newsblur_web ./manage.py migrate
 ---> Starting NewsBlur development server...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django_prometheus/db/common.py", line 45, in get_new_connection
    return super().get_new_connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db_postgres" to address: Name or service not known


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/newsblur/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 216, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django_prometheus/db/common.py", line 45, in get_new_connection
    return super().get_new_connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not translate host name "db_postgres" to address: Name or service not known

make: [Makefile:32: nb] Error 1 (ignored)
docker exec newsblur_web ./manage.py loaddata config/fixtures/bootstrap.json
 ---> Starting NewsBlur development server...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django_prometheus/db/common.py", line 45, in get_new_connection
    return super().get_new_connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No route to host
        Is the server running on host "db_postgres" (192.168.32.3) and accepting
        TCP/IP connections on port 5432?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/newsblur/./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 71, in handle
    with transaction.atomic(using=self.using):
  File "/usr/local/lib/python3.9/site-packages/django/db/transaction.py", line 175, in __enter__
    if not connection.get_autocommit():
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 389, in get_autocommit
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django_prometheus/db/common.py", line 45, in get_new_connection
    return super().get_new_connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: No route to host
        Is the server running on host "db_postgres" (192.168.32.3) and accepting
        TCP/IP connections on port 5432?

make: [Makefile:33: nb] Error 1 (ignored)

```

**Comment by samuelclay** [comment]
What do the logs of those misbehaving contains say? `docker logs db_postgres` and `docker logs db_mongo` and `docker logs imageproxy`.

**Comment by SinSharks** [comment]
Hello Everyone, I haven't diffed the current master with this tag yet but have discovered if you take the last verified version: 969d60ecc875db10fa7c66485be02507c5c554f5 that was put out before this issue was posted. Newsblur build/make(s) correctly. This suggest the bug was introduced sometime between these 2 versions: 

Working version:
969d60ecc875db10fa7c66485be02507c5c554f5
May 17, 2022

Broken sometime/before:
f6f0738acd330337de8329a40906122383a2108f
on May 21, 2022

**Comment by samuelclay** [comment]
Closing — the Docker setup has been substantially reworked since this May 2022 report, including Elasticsearch 8 upgrade, Python 3.13/3.14 upgrades, MongoDB version changes, container renaming, and Docker Compose v2 migration. Please try a fresh `make` if still having issues.
