### ISSUE TITLE
Android: Crash on "Widget"

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1706]
**To Reproduce**

1. Click on 3dot menu
2. Widget...
3. App crashes

**Crash logs:**

```
FATAL EXCEPTION: main
Process: com.newsblur, PID: 28391
java.lang.NullPointerException: Attempt to invoke virtual method 'com.newsblur.util.ImageLoader$PhotoToLoad com.newsblur.util.ImageLoader.displayImage(java.lang.String, android.widget.ImageView, int, boolean)' on a null object reference
 at com.newsblur.activity.FeedChooserAdapter.getChildView(FeedChooserAdapter.java:149)
 at com.newsblur.activity.WidgetConfigAdapter.getChildView(WidgetConfigAdapter.java:52)
 at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
 at android.widget.AbsListView.obtainView(AbsListView.java:2388)
 at android.widget.ListView.makeAndAddView(ListView.java:2052)
 at android.widget.ListView.fillDown(ListView.java:786)
 at android.widget.ListView.fillFromTop(ListView.java:847)
 at android.widget.ListView.layoutChildren(ListView.java:1798)
 at android.widget.AbsListView.onLayout(AbsListView.java:2187)
 at android.view.View.layout(View.java:19663)
 at android.view.ViewGroup.layout(ViewGroup.java:6075)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:19663)
 at android.view.ViewGroup.layout(ViewGroup.java:6075)
 at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
 at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
 at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2003)
 at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
 at android.view.View.layout(View.java:19663)
 at android.view.ViewGroup.layout(ViewGroup.java:6075)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:19663)
 at android.view.ViewGroup.layout(ViewGroup.java:6075)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:19663)
 at android.view.ViewGroup.layout(ViewGroup.java:6075)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:19663)
 at android.view.ViewGroup.layout(ViewGroup.java:6075)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
 at android.view.View.layout(View.java:19663)
 at android.view.ViewGroup.layout(ViewGroup.java:6075)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
 at android.view.View.layout(View.java:19663)
 at android.view.ViewGroup.layout(ViewGroup.java:6075)
 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2500)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2216)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1396)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6773)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
 at android.view.Choreographer.doCallbacks(Choreographer.java:778)
 at android.view.Choreographer.doFrame(Choreographer.java:713)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6518)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
App version: 11.3.1 (203)

**Comment by sictiru** [comment]
Fixed in NewsBlur v12.0
