### ISSUE TITLE
[Self Hosted] Server error in new install (custom domain)

### ISSUE THREAD

**Issue by Linecutterx** [samuelclay/NewsBlur#1717]
I'm not quite sure how to fix this one (/srv/newsblur/media/css/reader/reader.css exists, looks to contain the right stuff & is owned by my user)

To reproduce:
- 'git clone' into a new NewsBlur folder.

- Run the custom_domain.sh script (needs moving & chmod +x, but I'll do that as a pull request) to my_domain.tld
- Change docker-compose haproxy ports to avoid clashes (these are the same as in my previous, working, version)
```
ports:
      - 1180:80
      - 11443:443
```
`make nb` goes OK & logs seem fine.
- Open the web page (at the custom domain) the there is an error page & the logs read:

```
---> Starting NewsBlur development server...

[Jul 24 20:53:18]  ---> [FF    ] [0.02s] [AnonymousUser] Loading welcome

[Jul 24 20:53:19] Internal Server Error: /

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner

    response = get_response(request)

  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback

    return callback(request, *args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func

    response = view_func(request, *args, **kwargs)

  File "/srv/newsblur/utils/view_functions.py", line 32, in wrapper

    return render(request, output[1], output[0])

  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/templates.py", line 95, in render

    return real_render(request, template_name, context, *args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render

    content = loader.render_to_string(template_name, context, request, using=using)

  File "/usr/local/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string

    return template.render(context, request)

  File "/usr/local/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render

    return self.template.render(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 170, in render

    return self._render(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render

    return self.nodelist.render(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render

    bit = node.render_annotated(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

    return self.render(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render

    return compiled_parent._render(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 162, in _render

    return self.nodelist.render(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render

    bit = node.render_annotated(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

    return self.render(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/defaulttags.py", line 39, in render

    output = self.nodelist.render(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 938, in render

    bit = node.render_annotated(context)

  File "/usr/local/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated

    return self.render(context)

  File "/usr/local/lib/python3.9/site-packages/pipeline/templatetags/pipeline.py", line 136, in render

    return self.render_compressed(package, package_name, 'css')

  File "/usr/local/lib/python3.9/site-packages/pipeline/templatetags/pipeline.py", line 69, in render_compressed

    return self.render_compressed_sources(package, package_name,

  File "/usr/local/lib/python3.9/site-packages/pipeline/templatetags/pipeline.py", line 112, in render_compressed_sources

    return method(package, paths, templates=templates)

  File "/usr/local/lib/python3.9/site-packages/pipeline/templatetags/pipeline.py", line 148, in render_individual_css

    tags = [self.render_css(package, path) for path in paths]

  File "/usr/local/lib/python3.9/site-packages/pipeline/templatetags/pipeline.py", line 148, in <listcomp>

    tags = [self.render_css(package, path) for path in paths]

  File "/usr/local/lib/python3.9/site-packages/pipeline/templatetags/pipeline.py", line 143, in render_css

    'url': mark_safe(staticfiles_storage.url(path))

  File "/srv/newsblur/utils/pipeline_utils.py", line 14, in url

    url = super().url(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 147, in url

    return self._url(self.stored_name, name, force)

  File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 126, in _url

    hashed_name = hashed_name_func(*args)

  File "/usr/local/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name

    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)

ValueError: Missing staticfiles manifest entry for 'css/reader/reader.css'
```

**Comment by SeptemberHX** [comment]
I meet the same problem on Ubuntu 20.04.

After cloning the repo, I changed nothing and just run `make nb`. It finished successfully and all the containers are started. The error appears when trying to visit the page: `ValueError: Missing staticfiles manifest entry for 'css/reader/reader.css'`

**Comment by SeptemberHX** [comment]
The problem was solved after running `make collectstatic`

**Comment by samuelclay** [comment]
Ok, I'm going to add `make collectstatic` to the `make nb` command. It's bit too many people and you don't have to run `make nb` all the time, only when things break (which they do a few times a year).
