### ISSUE TITLE
Android: App crashes on Export OPML

### ISSUE THREAD

**Issue by shuvashish76** [samuelclay/NewsBlur#1891]
Logs:

```
FATAL EXCEPTION: main
Process: com.newsblur, PID: 5981
java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/NewsBlur-OPML-newsblur76.xml: Neither user 10368 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
	at android.content.ContentResolver.insert(ContentResolver.java:1588)
	at android.app.DownloadManager.enqueue(DownloadManager.java:1032)
	at i1.q.onClick(SourceFile:147)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Instead of crash it should ask for the relevant permission to the user.

App version : 13.3.0
Source : F-Droid

**Comment by sictiru** [comment]
@shuvashish76 What device and android version is this from?

**Comment by shuvashish76** [comment]
Lenovo Tab4 8 plus (TB-8704X), Android 9

**Comment by sictiru** [comment]
Pushed to production

**Comment by shuvashish76** [comment]
Don't forget to push tags on releases for F-Droid...🫣
