### ISSUE TITLE
When running CELERYBEAT_SCHEDULE task feeds, the error happen

### ISSUE THREAD

**Issue by neoszc** [samuelclay/NewsBlur#471]
Task task-feeds[a9a059cf-9d47-4a14-bb7c-69b9b989133c] raised exception: ResponseError("ERR wrong number of arguments for 'sadd' command",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery-3.0.17-py2.7.egg/celery/task/trace.py", line 228, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery-3.0.17-py2.7.egg/celery/task/trace.py", line 415, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/newsblur/apps/rss_feeds/tasks.py", line 28, in run
    r.sadd('queued_feeds', *queued_feeds)
  File "/usr/local/lib/python2.7/dist-packages/redis-2.8.0-py2.7.egg/redis/client.py", line 1092, in sadd
    return self.execute_command('SADD', name, *values)
  File "/usr/local/lib/python2.7/dist-packages/redis-2.8.0-py2.7.egg/redis/client.py", line 394, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis-2.8.0-py2.7.egg/redis/client.py", line 404, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis-2.8.0-py2.7.egg/redis/connection.py", line 316, in read_response
    raise response
ResponseError: ERR wrong number of arguments for 'sadd' command
[2014-01-19 08:58:01,633: INFO/MainProcess] Task collect-feedback[0e7c697c-3477-4e30-89da-9dcb1d5b1ff6] succeeded in 1.2539870739s: None

**Comment by thangappan** [comment]
What should be the way to resolve this.
We are also facing the same issue.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 228, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 415, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/ky59zrp/apps/newsblur/installation/NewsBlur/apps/rss_feeds/tasks.py", line 28, in run
    r.sadd('queued_feeds', *queued_feeds)
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 1092, in sadd
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 394, in execute_command
  File "build/bdist.linux-x86_64/egg/redis/client.py", line 404, in parse_response
  File "build/bdist.linux-x86_64/egg/redis/connection.py", line 316, in read_response
ResponseError: ERR wrong number of arguments for 'sadd' command

<code>
r.sadd('queued_feeds', *queued_feeds)
</code>

The above code is returning 0 feeds.

Please help us to resolve..

**Comment by samuelclay** [comment]
Can you ensure that you have enough feeds that need fetching? It's possible this is failing because there are no stale feeds.

**Comment by thangappan** [comment]
Thanks for your response.
I was looking into celery jobs because of the auto refresh is not happening.

Which celery job is refreshing the feeds automatically and the error above have any connection with the auto refresh??

**Comment by samuelclay** [comment]
Does that command ever work? Most feeds should fetch at least once an hour.

**Comment by thangappan** [comment]
The command is working fine without any issues.

./manage.py refresh_feeds --force 

Auto refresh is not working through celery.
Help would be appreciated
