### ISSUE TITLE
code 400, message Bad request in development server

### ISSUE THREAD

**Issue by thangappan** [samuelclay/NewsBlur#642]
Hi,

Doing the fresh installation on Ubuntu 14.04. 
When I started the development server ( ./manage.py runserver )  getting the following exception.

[23/Dec/2014 06:11:23] code 400, message Bad request syntax ('\x16\x03\x00\x00?\x01\x00\x00;\x03\x00\xd8\xa8\x87A\xe1zg\x1d\xed\xec\x03W\xf3\x99\x91\xa5\x04\x9f@\x11\xa5\x85t\xddwK\x022]oK4\x00\x00\x14\x00\xffV\x00\x003\x002\x009\x00/\x005\x00')
----------------------------------------
Exception happened during processing of request from ('10.237.177.36', 52543)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.5.11-py2.7.egg/django/core/servers/basehttp.py", line 143, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/local/lib/python2.7/dist-packages/Django-1.5.11-py2.7.egg/django/core/servers/basehttp.py", line 155, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x87 in position 14: invalid start byte

It causes the following issues
* Created user is not able to login 
* Couldn't add a new site 

Could you please take a look at it?

**Comment by thangappan** [comment]
Hi,

Still facing the same issue. Couldn't rectify it. 
Could you please guide me to solve the problem?

**Comment by samuelclay** [comment]
Yes, you need a `sitecustomize.py` file in your `PYTHONPATH`. See NewsBlur's sitecustomize.py file, which has this:

```
import sys
sys.setdefaultencoding('utf-8')

import os
os.putenv('LANG', 'en_US.UTF-8')
os.putenv('LC_ALL', 'en_US.UTF-8')
```

**Comment by thangappan** [comment]
Thanks for the reply.

The specified file is already in PYTHONPATH. I verified it by checking the defaultencoding from the sys module.

<pre lang="python"><code>
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>>
</code></pre>

The error also shows properly that, it uses "UTF-8" encoding.

<pre>
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa7 in position 12: invalid start byte
</pre>

Could you please help me?

**Comment by samuelclay** [comment]
How are you running the web server? Is it just off `manage.py runserver`? This looks like a web server I haven't used. I use gunicorn in front of django.

**Comment by thangappan** [comment]
Yes. I tried two ways.

One is running with development server ./manage.py runserver 
Another one is configured with Apache and run it.

Both the ways getting the same error 

<pre>

07/Jan/2015 05:59:15 code 400, message Bad request syntax ('\x16\x03\x00\x00?\x01\x00\x00;\x03\x00%\x8f\x0f\xec\x99%\xc3\xc4\xac\x1e\xae\xbe\x92\xde/\xb3)\xe5\xbeG\x85\x07m\x1bA\x83\xc9|\xb3\x80\xcd\x9d\x00\x00\x14\x00\xffV\x00\x003\x002\x009\x00/\x005\x00')

Exception happened during processing of request from ('xxxxxxxxxxx', 53551)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.5.11-py2.7.egg/django/core/servers/basehttp.py", line 143, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/lib/python2.7/wsgiref/simple_server.py", line 117, in handle
    if not self.parse_request(): # An error code has been sent, just exit
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 368, in send_error
    self.send_response(code, message)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 385, in send_response
    self.log_request(code)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 422, in log_request
    self.requestline, str(code), str(size))
  File "/usr/local/lib/python2.7/dist-packages/Django-1.5.11-py2.7.egg/django/core/servers/basehttp.py", line 155, in log_message
    msg = "[%s] %s\n" % (self.log_date_time_string(), format % args)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8f in position 13: invalid start byte

</pre>

Did I miss out anything?

**Comment by samuelclay** [comment]
I just don't know, since it doesn't look like the error is in NewsBlur's code at all.

**Comment by thangappan** [comment]
Hi

Finally I am able to resolve issue by cleaning up everything and start from scratch.
Now I didn't get same error as mentioned above.

When I set debug = False in my settings page and load the newsblur home page.
it failed with the following error

<pre>
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/thangappan/NEWSBLUR/NewsBlur/utils/view_functions.py", line 34, in wrapper
    return render_to_response(output[1], output[0], RequestContext(request))
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 177, in render_to_string
    return t.render(context_instance)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 844, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 1114, in render
    return func(*resolved_args, **resolved_kwargs)
  File "/home/thangappan/NEWSBLUR/NewsBlur/utils/templatetags/utils_tags.py", line 187, in include_stylesheets
    return settings.JAMMIT.render_tags(asset_type, asset_package)
  File "/home/thangappan/NEWSBLUR/NewsBlur/utils/jammit.py", line 47, in render_tags
    tag = self.stylesheet_tag_compressed(asset_package, asset_type_ext)
  File "/home/thangappan/NEWSBLUR/NewsBlur/utils/jammit.py", line 108, in stylesheet_tag_compressed
    asset_mtime = int(os.path.getmtime(datauri_filename))
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: 'static/common-datauri.css'
[13/Jan/2015 11:22:50] "GET / HTTP/1.1" 500 874
</pre>

But when I do debug = True and load the page, it loads the page but couldn't login with the created user. It always loads the home page when I click login button.

Could you please help me to resolve this issue?

**Comment by samuelclay** [comment]
It's probably your cookie domain. I use nb.local.com, which is set in my /etc/hosts to point to localhost. And in my local settings:

```SESSION_COOKIE_DOMAIN = ".nb.local.com"```

**Comment by thangappan** [comment]
I tried the same. Still getting the same error.
When I set True value to DEBUG mode, able to see the newsblur home page.
But couldn't login with created user and couldn't add any site.

Please provide some help to resolve this issue.

**Comment by samuelclay** [comment]
Can you provide a full browser screenshot? Make sure to add the domain to /etc/hosts and use that domain as your cookie domain.

**Comment by thangappan** [comment]
Here I attach the screen shots. Please refer it.
![image](https://cloud.githubusercontent.com/assets/5318704/5771721/5adcdf56-9d69-11e4-80ee-b6c72dfc497a.png)
![image](https://cloud.githubusercontent.com/assets/5318704/5771724/75b171d4-9d69-11e4-8c66-b6910e690d1d.png)

**Comment by samuelclay** [comment]
I'm not sure that the cookie domain can be an invalid URL. Try turning it into a valid domain.

**Comment by thangappan** [comment]
Hi,

I also tried the domain name that you suggested. ( nb.local.com ) and added that entry in /etc/hosts.
still getting the same error. 
Not able to use the newsblur app.

Please help me to resolve this issue.

**Comment by samuelclay** [comment]
Wait, you're getting an error now? If it's that static-common error, you'll want to install jammit and run `fab pre_deploy` to generate those static files. But if you plan to change those files regularly and don't want to have to package the assets every time (although thats what I do), turn on `DEBUG=True`.

**Comment by thangappan** [comment]
Ok. As you suggested I turned on DEBUG=True.
When I hit the browser with the hostname, able to see the login page.
I created a user and tried adding one site. The site is not adding.
It says "there was a problem adding that site"

Found the following lines from the logs 

<pre>
[Jan 21 08:29:14] {u'term': u'http://www.thehindu.com/news/international/world/?service=rss'}
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
[Jan 21 08:29:15] Search feeds by address: www.thehindu.com news international world
[Jan 21 08:29:15] Search feeds by title: www.thehindu.com news international world
[Jan 21 08:29:15] Search feeds by link: www.thehindu.com news international world
[Jan 21 08:29:15] Search feeds by address: www.thehindu.com news international
[Jan 21 08:29:15] Search feeds by title: www.thehindu.com news international
[Jan 21 08:29:15] Search feeds by link: www.thehindu.com news international
[Jan 21 08:29:15] Search feeds by address: www.thehindu.com news
[Jan 21 08:29:15] Search feeds by title: www.thehindu.com news
[Jan 21 08:29:15] Search feeds by link: www.thehindu.com news
[Jan 21 08:29:15] Search feeds by address: www.thehindu.com
[Jan 21 08:29:15] Search feeds by title: www.thehindu.com
[Jan 21 08:29:15] Search feeds by link: www.thehindu.com
[Jan 21 08:29:15]  ---> [Chrome] [1.11s] [AnonymousUser] Add Search: www.thehindu.com news international world (0 matches)
[21/Jan/2015 08:29:15] "GET /rss_feeds/feed_autocomplete?term=http%3A%2F%2Fwww.thehindu.com%2Fnews%2Finternational%2Fworld%2F%3Fservice%3Drss HTTP/1.1" 200 2
[Jan 21 08:29:16] {u'url': u'http://www.thehindu.com/news/international/world/?service=rss', u'folder': u'', u'auto_active': u'true'}
[21/Jan/2015 08:29:16] "POST /reader/add_url/ HTTP/1.1" 403 0
[21/Jan/2015 08:29:16] "GET /media/img/reader/spinner_ball.gif HTTP/1.1" 304 0
</pre>

Then logged out and tried login with that user. when I click login button it loads only the login page.
there was no error notification about "Login failed"

Checked the newsblur logs. Found the following lines

<pre>
[Jan 21 08:36:04]  ---> [Chrome] [0.00s] [AnonymousUser] Loading welcome
[21/Jan/2015 08:36:04] "GET / HTTP/1.1" 200 7484
[Jan 21 08:36:05] {u'v': u'2'}
[21/Jan/2015 08:36:05] "GET /reader/feeds?v=2 HTTP/1.1" 200 68
[Jan 21 08:36:11] {u'login-username': u'test', u'login-password': u'test', u'submit': u'log in', u'next': u'/'}
[Jan 21 08:36:11]  ---> [------] [test*] Login
[21/Jan/2015 08:36:11] "POST /reader/login HTTP/1.1" 302 0
[Jan 21 08:36:11]  ---> [Chrome] [0.00s] [AnonymousUser] Loading welcome
[21/Jan/2015 08:36:11] "GET / HTTP/1.1" 200 7484
[Jan 21 08:36:12] {u'v': u'2'}
[21/Jan/2015 08:36:12] "GET /reader/feeds?v=2 HTTP/1.1" 200 68
</pre>

What could be the issue?
Did I miss out anything ?

**Comment by samuelclay** [comment]
What cookies do you have? Can you post a screenshot? It's supposed to be setting a `newsblur_sessionid` cookie on the domain you set above. 

Also, try logging into the admin. nb.local.com/admin/

**Comment by giladsh1** [comment]
maybe it's because of an https request?
try - 
 `pip install pyopenssl`
and add to your script - 
```
if __name__ == '__main__':
    app.run(port=4567,host='0.0.0.0',ssl_context='adhoc')
```

**Comment by ugurcanb** [comment]
i experienced the same problem and ssl_context='adhoc' worked for me. problem is about ssl request.

**Comment by hygull** [comment]
In my case the issue was related to **protocol** i.e. **https**/**http**. I had used **https://127.0.0.1:800** in place of **http://127.0.0.1:8000**.

Changing it to **http** worked and this indication was clear in error message itself.

Just have look at below logs

```bash
(venv3.6.7) Rishikeshs-MacBook-Air:src hygull$ python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
October 12, 2019 - 21:27:15
Django version 2.2.6, using settings 'apiserver.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[12/Oct/2019 21:27:16] code 400, message Bad request version ('cë¹\x02-%â%\x8cd\x8fw\x88')
[12/Oct/2019 21:27:16] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Oct/2019 21:27:16] code 400, message Bad request version ('\x82Y§\x03\x07rDF),3S\x97#«¤A\x8c\x9aâ\x88,\'{ÒU\x134ÔÅ3Ü\x00"**\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[12/Oct/2019 21:27:16] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Oct/2019 21:27:17] code 400, message Bad request version ('ZÌæÃ\x03')
[12/Oct/2019 21:27:17] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Oct/2019 21:27:17] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03ò\x97Â\x9bæp;Ô«Ng.\x91×>\x11ª-\x9e&:\x06p\x06\tÉ^èe¢4p »Ä\x8c\x95\\\x0bA\x1fV\x04)#4-4\x89|M \x11Ö¨O¶C°ùJðµJ+\x00"\x9a\x9a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[12/Oct/2019 21:27:17] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Oct/2019 21:27:18] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\r°\x83\x9bI¥\x1cZ]ÐW¾Y\x8b\x1dÍVî\x84\x9b\t²\x10¡\x89r\x8bº½\x8cçÆ ²ÄÒ\x1fì\x1b^<Uºe´\x0f\x86áñ}{7¹£]!¼?²\x13¸¶(U\x16\x00"')
[12/Oct/2019 21:27:18] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Oct/2019 21:27:18] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03a¥_Ðc\x1ft\x9dtÔÜ`Ï+{\x01×ù|\x82ß¸=R%³¥gÃ0º* £5øà÷ê\x13\x91Ñ«anÚ¹Ã R¶c\\=i\x81â¾ª9»î¿ó¹\x00"\x9a\x9a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[12/Oct/2019 21:27:18] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Oct/2019 21:27:19] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03ÛHìØIá\x1d)©6\x03uèEà\x07\x18Çß\x9d©_:\x17\x0e&:á\x179T\x91 \x14ÕÑb½ßÙôE×\x9cy\x07¡Ê\t·\x02´V1=\x91ß®õj4\x8dy¿\x11\x00"ªª\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[12/Oct/2019 21:27:19] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Oct/2019 21:28:14] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03.×´7c [H)×c\x0eª\x87\x10Ö\x82+Ó\r\x95C*óäzæ\x1fx\x043c \x8e9\x98ç~\x0e\rª\x80\x97\x86_"ø§Zî2*p`Er\x9a¸¨\'ß\t\x9dâh\x00"ZZ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[12/Oct/2019 21:28:14] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Oct/2019 21:28:18] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03ðÜ\rÐ\x83ýïN\x02ÿ\x17\x90÷±$u«§\x12F1.\x95"\x1d4Í\x86#OÀ" Õ¬<¢\t]\x9d¬\x17\x18Y«;2\x8a®\x97¿´ÂB\x14i\\Î"¹\x9e÷34.\x00"ÊÊ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[12/Oct/2019 21:28:18] You're accessing the development server over HTTPS, but it only supports HTTP.

[12/Oct/2019 21:30:16] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03p¼uÒ\x8fh\x98?ª0\x05üEïÃ\x1e\xa0Kí\x00\x05æ\x1a1P¨ªNæ15í \x9bUÑèp¦ÓÔjp¨¡Ñÿü\x07\x8füÀ0ÀíÊ\x85\x8aýQ\x04àæÃS\x00"ºº\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[12/Oct/2019 21:30:16] You're accessing the development server over HTTPS, but it only supports HTTP.
```

Now, after issue fix.

```bash
...
Request Data <QueryDict: {'limit': ['3'], 'offset': ['1']}>
offset 2 limit 2
filters {}
{'data': {'images': [OrderedDict([('pk', 3), ('url', 'https://raw.githubusercontent.com/hygull/fileserver/master/2019/screenshots/get_modal_configs_1.png'), ('caption', 'Get modal configurations (Modal images), 1st'), ('created_at', '2019-10-08T22:23:06.448042+05:30'), ('updated_at', '2019-10-10T01:09:39.458509+05:30')]), OrderedDict([('pk', 4), ('url', 'https://raw.githubusercontent.com/hygull/fileserver/master/2019/screenshots/get_modal_configs_2.png'), ('caption', 'Get modal configurations (Modal images), 2nd'), ('created_at', '2019-10-08T22:23:34.067841+05:30'), ('updated_at', '2019-10-10T01:09:28.530747+05:30')])], 'total': 7}, 'status': 200, 'message': 'Successful'}
[12/Oct/2019 21:30:27] "POST /api/v1/files/images/?offset=2&limit=2 HTTP/1.1" 200 607
Request Data <QueryDict: {'limit': ['3'], 'offset': ['1']}>
offset 2 limit 2
filters {}
{'data': {'images': [OrderedDict([('pk', 3), ('url', 'https://raw.githubusercontent.com/hygull/fileserver/master/2019/screenshots/get_modal_configs_1.png'), ('caption', 'Get modal configurations (Modal images), 1st'), ('created_at', '2019-10-08T22:23:06.448042+05:30'), ('updated_at', '2019-10-10T01:09:39.458509+05:30')]), OrderedDict([('pk', 4), ('url', 'https://raw.githubusercontent.com/hygull/fileserver/master/2019/screenshots/get_modal_configs_2.png'), ('caption', 'Get modal configurations (Modal images), 2nd'), ('created_at', '2019-10-08T22:23:34.067841+05:30'), ('updated_at', '2019-10-10T01:09:28.530747+05:30')])], 'total': 7}, 'status': 200, 'message': 'Successful'}
[12/Oct/2019 21:30:49] "POST /api/v1/files/images/?offset=2&limit=2 HTTP/1.1" 200 607
```

**Comment by 4k45hv3rm4** [comment]
even I got the same error message while running my flask app server and checking it using postman , I was getting same error message as @hygull  but i was not getting the line . "You're accessing the development server over HTTPS, but it only supports HTTP." So i was confused but when i tried changing the https to http It worked .  Thanks to you guys ! I resolved it ....

![error_line](https://user-images.githubusercontent.com/30963535/71963223-330cae00-3221-11ea-80d1-209d283e237f.png)
