### ISSUE TITLE
manage.py error

### ISSUE THREAD

**Issue by sbilly** [samuelclay/NewsBlur#718]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 376, in execute
    sys.stdout.write(self.main_help_text() + '\n')
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 242, in main_help_text
    for name, app in six.iteritems(get_commands()):
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/root/NewsBlur/settings.py", line 567, in <module>
    RAVEN_CLIENT = raven.Client(SENTRY_DSN)
  File "/usr/local/lib/python2.7/dist-packages/raven/base.py", line 147, in __init__
    dsn_config = raven.load(dsn, transport_registry=self._registry)
  File "/usr/local/lib/python2.7/dist-packages/raven/conf/__init__.py", line 53, in load
    scope_extras = transport_registry.compute_scope(url, scope)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/registry.py", line 57, in compute_scope
    return transport.compute_scope(url, scope)
  File "/usr/local/lib/python2.7/dist-packages/raven/transport/base.py", line 188, in compute_scope
    raise ValueError('Invalid Sentry DSN: %r' % url.geturl())
ValueError: Invalid Sentry DSN: 'https://XXXNEWSBLURXXX@app.getsentry.com/99999999'

**Comment by samuelclay** [comment]
Like the error implies, you'll want your own Sentry DSN. Or just turn off Sentry, which is used as the error logger. I disable Sentry in DEBUG.

**Comment by sbilly** [comment]
https://github.com/samuelclay/NewsBlur/blob/97b0910e675c79d376e7988234bebc7f692b687d/settings.py#L560

It's enabled when is NOT development mode. How can I disable it?

**Comment by samuelclay** [comment]
Why not run with DEVELOPMENT = True?
