### ISSUE TITLE
Web: feed_fetcher.py error.

### ISSUE THREAD

**Issue by sbilly** [samuelclay/NewsBlur#758]
feed_fetcher.py error.

Traceback (most recent call last):
  File "/srv/newsblur/utils/feed_fetcher.py", line 684, in process_feed_wrapper
    icon_importer.save()
  File "/srv/newsblur/apps/rss_feeds/icon_importer.py", line 51, in save
    color     = self.determine_dominant_color_in_image(image)
  File "/srv/newsblur/apps/rss_feeds/icon_importer.py", line 310, in determine_dominant_color_in_image
    codes, _ = scipy.cluster.vq.kmeans(ar, NUM_CLUSTERS)
  File "/usr/local/lib/python2.7/dist-packages/scipy/cluster/vq.py", line 568, in kmeans
    book, dist = _kmeans(obs, guess, thresh=thresh)
  File "/usr/local/lib/python2.7/dist-packages/scipy/cluster/vq.py", line 436, in _kmeans
    code_book, has_members = _vq.update_cluster_means(obs, obs_code, nc)
  File "scipy/cluster/_vq.pyx", line 347, in scipy.cluster._vq.update_cluster_means (scipy/cluster/_vq.c:4564)
TypeError: type other than float or double not supported

**Comment by samuelclay** [comment]
What's the image URL that's causing this issue? I haven't seen it before.

**Comment by samuelclay** [comment]
Just figured this out. You're using a newer version of scipy. NewsBlur currently only works with 0.14.1. 0.15.0 breaks it. I'm fixing it right now. (Guess how I found this ticket ...)

**Comment by samuelclay** [comment]
In 6edbf67. Thanks!

**Comment by sbilly** [comment]
lol
hope it helps
