### ISSUE TITLE
Having trouble to install on local

### ISSUE THREAD

**Issue by FromBabylon** [samuelclay/NewsBlur#768]
I have followed the guidelines that @tonyduckles gave in #92 but I still have an issue at the very beginning : 

```
ubuntu@newsblur:/srv/newsblur$fab -H localhost setup_all
 ***> No role definitions found in /srv/secrets-newsblur/configs/hosts.yml. Using default roles.
 ---> You need to fix django's settings. Enter python and type `import settings`.
[localhost] Executing task 'setup_all'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 368, in execute
    multiprocessing
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 264, in _execute
    return task.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 171, in run
    return self.wrapped(*args, **kwargs)
  File "/srv/newsblur/fabfile.py", line 210, in setup_all
    setup_common()
  File "/srv/newsblur/fabfile.py", line 186, in setup_common
    setup_installs()
  File "/srv/newsblur/fabfile.py", line 341, in setup_installs
    put("config/apt_sources.conf", "/etc/apt/sources.list", use_sudo=True)
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 639, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 346, in put
    ftp = SFTP(env.host_string)
  File "/usr/local/lib/python2.7/dist-packages/fabric/sftp.py", line 30, in __init__
    self.ftp = connections[host_string].open_sftp()
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 151, in __getitem__
    self.connect(key)
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 143, in connect
    self[key] = connect(user, host, port, cache=self)
  File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 444, in connect
    sock=sock
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 273, in connect
    self._auth(username, password, pkey, key_filenames, allow_agent, look_for_keys)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 387, in _auth
    key = pkey_class.from_private_key_file(key_filename, password)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/pkey.py", line 177, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/rsakey.py", line 51, in __init__
    self._from_private_key_file(filename, password)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/rsakey.py", line 161, in _from_private_key_file
    data = self._read_private_key_file('RSA', filename, password)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/pkey.py", line 249, in _read_private_key_file
    f = open(filename, 'r')
IOError: [Errno 2] No such file or directory: '/srv/secrets-newsblur/keys/newsblur.key'
```
I don't see any key file and no one seems to have the same issue.

I am trying to install NewsBlur in an ubuntu LXC container. 

Any help ? 

Thanks

**Comment by samuelclay** [comment]
You'll need to use the secrets-newsblur-skel project in /srv/secrets-newsblur. https://github.com/charlesflynn/secrets-newsblur-skel

**Comment by FromBabylon** [comment]
Thanks for your reply. 
And if I don't want to use vagrant but just install NewsBlur in LXC container ?

**Comment by samuelclay** [comment]
Well I don't use Vagrant, so I'm not sure. The fabric script doesn't use containers. I should get with the times, but it's not a priority yet.

**Comment by FromBabylon** [comment]
I don't understand because I don't see where it's different from installing on host OS. I already have some webapps in LXC containers and one was installed using fabric. The only trick is to redirect from host to container using nginx/apache

**Comment by samuelclay** [comment]
Yeah, that's beyond my experience having never used Vagrant.

**Comment by FromBabylon** [comment]
But I don't want to use vagrant. Let's assume it's an ubuntu os, I would still have the same problem as there is no key file right ?

**Comment by samuelclay** [comment]
You'll want to comment out that line if you can't provide your own certificates. That key file is a ssl certificate. But you don't need it, just comment out that line.

Also, there's an error at the top of the output. You'll want to run 'from django.conf import settings' to find out what's causing the error.

**Comment by FromBabylon** [comment]
Thought nginx would handle ssl
Thanks a lot
