### ISSUE TITLE
Connection error on 6379

### ISSUE THREAD

**Issue by FromBabylon** [samuelclay/NewsBlur#822]
I manage to install things but it was really painful :) 
First should I run `fab -R local setup_app`and the two other commands if I install using setup_all ? Cause those commands return that no local role has been defined. 

If I run the server using `./manage.py runserver`it starts but when I try to reach it I got this error : 
```
ERROR:django.request:Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/newsblur/utils/view_functions.py", line 32, in wrapper
    output = func(request, *args, **kw)
  File "/srv/newsblur/apps/reader/views.py", line 85, in index
    return welcome(request, **kwargs)
  File "/srv/newsblur/apps/reader/views.py", line 127, in welcome
    user              = get_user(request)
  File "/srv/newsblur/utils/user_functions.py", line 83, in get_user
    user = cache.get('user:%s' % settings.HOMEPAGE_USERNAME, None)
  File "/usr/local/lib/python2.7/dist-packages/redis_cache/cache.py", line 179, in get
    value = self._client.get(key)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 863, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 570, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 556, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 532, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 436, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
```

Nothing is listening on 127.0.0.1:6379. 

How to process ?

**Comment by FromBabylon** [comment]
I tried to do a clean install again. This time installation return this error : 
```
[localhost] out: Traceback (most recent call last):
[localhost] out:   File "utils/backups/s3.py", line 56, in <module>
[localhost] out:     get_file_from_s3(sys.argv[2])
[localhost] out:   File "utils/backups/s3.py", line 26, in get_file_from_s3
[localhost] out:     bucket = conn.get_bucket(BUCKET_NAME)
[localhost] out:   File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 409, in get_bucket
[localhost] out:     bucket.get_all_keys(headers, maxkeys=0)
[localhost] out:   File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 371, in get_all_keys
[localhost] out:     '', headers, **params)
[localhost] out:   File "/usr/local/lib/python2.7/dist-packages/boto/s3/bucket.py", line 338, in _get_all
[localhost] out:     response.status, response.reason, body)
[localhost] out: boto.exception.S3ResponseError: S3ResponseError: 403 Forbidden
[localhost] out: <?xml version="1.0" encoding="UTF-8"?>
[localhost] out: <Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>XXX</AWSAccessKeyId><RequestId>5AE6E209E1E53B27</RequestId><HostId>5p7rmc+v06l+aezo9pgfYfgFeL6wpc57C6xtum5Kl1z266jpqblbxje9uRD93JhoP4aP4ij5/ac=</HostId></Error>
[localhost] out:


Fatal error: run() received nonzero return code 1 while executing!

Requested: PYTHONPATH=/srv/newsblur python utils/backups/s3.py get static.tgz
Executed: /bin/bash -l -c "cd /srv/newsblur && PYTHONPATH=/srv/newsblur python utils/backups/s3.py get static.tgz"
```

**Comment by samuelclay** [comment]
The first error means you aren't running Redis. The second error means that your AWS key is invalid. You should specify a valid AWS key in local_settings.py. Although why are you using AWS? I use it for static assets, but you should just use DEBUG_ASSETS=True in local_settings.py, since you don't need to optimize for bandwidth like the hosted NewsBlur does.

**Comment by FromBabylon** [comment]
Well, I didn't want to use it but didn't know how to disable. Cause I get the same error with DEBUG_ASSETS=True

**Comment by samuelclay** [comment]
Comment out the problematic lines from the install, like using S3.

**Comment by FromBabylon** [comment]
I'm not sure which lines I should comment without compromising the install. 
And Why didn't I get this problem earlier ? Cause I once got the install work without commenting out any lines..

**Comment by FromBabylon** [comment]
Well I comment out the transfert assets and also had to comment out 'elif engine.startwith ...' cause None object can't do that. 
It works and I can reach it but got some other problems now :) 
Posting a new issue
